// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/listing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main listing information
type Listing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PersonalInfo  *PersonalInfo          `protobuf:"bytes,2,opt,name=personal_info,json=personalInfo,proto3" json:"personal_info,omitempty"`
	ContactInfo   *ContactInfo           `protobuf:"bytes,3,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	PricingInfo   *PricingInfo           `protobuf:"bytes,4,opt,name=pricing_info,json=pricingInfo,proto3" json:"pricing_info,omitempty"`
	ServiceInfo   *ServiceInfo           `protobuf:"bytes,5,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	LocationInfo  *LocationInfo          `protobuf:"bytes,6,opt,name=location_info,json=locationInfo,proto3" json:"location_info,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	LastUpdated   string                 `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Photos        []string               `protobuf:"bytes,9,rep,name=photos,proto3" json:"photos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_proto_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Listing) GetPersonalInfo() *PersonalInfo {
	if x != nil {
		return x.PersonalInfo
	}
	return nil
}

func (x *Listing) GetContactInfo() *ContactInfo {
	if x != nil {
		return x.ContactInfo
	}
	return nil
}

func (x *Listing) GetPricingInfo() *PricingInfo {
	if x != nil {
		return x.PricingInfo
	}
	return nil
}

func (x *Listing) GetServiceInfo() *ServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

func (x *Listing) GetLocationInfo() *LocationInfo {
	if x != nil {
		return x.LocationInfo
	}
	return nil
}

func (x *Listing) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Listing) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *Listing) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

// Personal information
type PersonalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Weight        int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	BreastSize    int32                  `protobuf:"varint,5,opt,name=breast_size,json=breastSize,proto3" json:"breast_size,omitempty"`
	HairColor     string                 `protobuf:"bytes,6,opt,name=hair_color,json=hairColor,proto3" json:"hair_color,omitempty"`
	EyeColor      string                 `protobuf:"bytes,7,opt,name=eye_color,json=eyeColor,proto3" json:"eye_color,omitempty"`
	BodyType      string                 `protobuf:"bytes,8,opt,name=body_type,json=bodyType,proto3" json:"body_type,omitempty"`
	Photos        []string               `protobuf:"bytes,9,rep,name=photos,proto3" json:"photos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalInfo) Reset() {
	*x = PersonalInfo{}
	mi := &file_proto_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInfo) ProtoMessage() {}

func (x *PersonalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInfo.ProtoReflect.Descriptor instead.
func (*PersonalInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{1}
}

func (x *PersonalInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonalInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PersonalInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PersonalInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PersonalInfo) GetBreastSize() int32 {
	if x != nil {
		return x.BreastSize
	}
	return 0
}

func (x *PersonalInfo) GetHairColor() string {
	if x != nil {
		return x.HairColor
	}
	return ""
}

func (x *PersonalInfo) GetEyeColor() string {
	if x != nil {
		return x.EyeColor
	}
	return ""
}

func (x *PersonalInfo) GetBodyType() string {
	if x != nil {
		return x.BodyType
	}
	return ""
}

func (x *PersonalInfo) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

// Contact information
type ContactInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Phone            string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	HasTelegram      bool                   `protobuf:"varint,2,opt,name=has_telegram,json=hasTelegram,proto3" json:"has_telegram,omitempty"`
	HasWhatsapp      bool                   `protobuf:"varint,3,opt,name=has_whatsapp,json=hasWhatsapp,proto3" json:"has_whatsapp,omitempty"`
	HasViber         bool                   `protobuf:"varint,4,opt,name=has_viber,json=hasViber,proto3" json:"has_viber,omitempty"`
	TelegramUsername string                 `protobuf:"bytes,5,opt,name=telegram_username,json=telegramUsername,proto3" json:"telegram_username,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContactInfo) Reset() {
	*x = ContactInfo{}
	mi := &file_proto_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfo) ProtoMessage() {}

func (x *ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfo.ProtoReflect.Descriptor instead.
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{2}
}

func (x *ContactInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ContactInfo) GetHasTelegram() bool {
	if x != nil {
		return x.HasTelegram
	}
	return false
}

func (x *ContactInfo) GetHasWhatsapp() bool {
	if x != nil {
		return x.HasWhatsapp
	}
	return false
}

func (x *ContactInfo) GetHasViber() bool {
	if x != nil {
		return x.HasViber
	}
	return false
}

func (x *ContactInfo) GetTelegramUsername() string {
	if x != nil {
		return x.TelegramUsername
	}
	return ""
}

// Pricing information
type PricingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HourPrice     int32                  `protobuf:"varint,1,opt,name=hour_price,json=hourPrice,proto3" json:"hour_price,omitempty"`
	TwoHourPrice  int32                  `protobuf:"varint,2,opt,name=two_hour_price,json=twoHourPrice,proto3" json:"two_hour_price,omitempty"`
	NightPrice    int32                  `protobuf:"varint,3,opt,name=night_price,json=nightPrice,proto3" json:"night_price,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricingInfo) Reset() {
	*x = PricingInfo{}
	mi := &file_proto_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingInfo) ProtoMessage() {}

func (x *PricingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingInfo.ProtoReflect.Descriptor instead.
func (*PricingInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{3}
}

func (x *PricingInfo) GetHourPrice() int32 {
	if x != nil {
		return x.HourPrice
	}
	return 0
}

func (x *PricingInfo) GetTwoHourPrice() int32 {
	if x != nil {
		return x.TwoHourPrice
	}
	return 0
}

func (x *PricingInfo) GetNightPrice() int32 {
	if x != nil {
		return x.NightPrice
	}
	return 0
}

func (x *PricingInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Service information
type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceInfo) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ServiceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Location information
type LocationInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MetroStations    []string               `protobuf:"bytes,1,rep,name=metro_stations,json=metroStations,proto3" json:"metro_stations,omitempty"`
	District         string                 `protobuf:"bytes,2,opt,name=district,proto3" json:"district,omitempty"`
	City             string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	OutcallAvailable bool                   `protobuf:"varint,4,opt,name=outcall_available,json=outcallAvailable,proto3" json:"outcall_available,omitempty"`
	IncallAvailable  bool                   `protobuf:"varint,5,opt,name=incall_available,json=incallAvailable,proto3" json:"incall_available,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LocationInfo) Reset() {
	*x = LocationInfo{}
	mi := &file_proto_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationInfo) ProtoMessage() {}

func (x *LocationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationInfo.ProtoReflect.Descriptor instead.
func (*LocationInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{5}
}

func (x *LocationInfo) GetMetroStations() []string {
	if x != nil {
		return x.MetroStations
	}
	return nil
}

func (x *LocationInfo) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *LocationInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *LocationInfo) GetOutcallAvailable() bool {
	if x != nil {
		return x.OutcallAvailable
	}
	return false
}

func (x *LocationInfo) GetIncallAvailable() bool {
	if x != nil {
		return x.IncallAvailable
	}
	return false
}

// PageInfo represents pagination information for main page scraping
type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	HasNext       bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrevious   bool                   `protobuf:"varint,4,opt,name=has_previous,json=hasPrevious,proto3" json:"has_previous,omitempty"`
	ListingUrls   []string               `protobuf:"bytes,5,rep,name=listing_urls,json=listingUrls,proto3" json:"listing_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_proto_listing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{6}
}

func (x *PageInfo) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PageInfo) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PageInfo) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *PageInfo) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

func (x *PageInfo) GetListingUrls() []string {
	if x != nil {
		return x.ListingUrls
	}
	return nil
}

// BatchResult represents the result of batch processing multiple listings
type BatchResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalPages        int32                  `protobuf:"varint,1,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	CurrentPage       int32                  `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalListings     int32                  `protobuf:"varint,3,opt,name=total_listings,json=totalListings,proto3" json:"total_listings,omitempty"`
	SuccessfulScrapes int32                  `protobuf:"varint,4,opt,name=successful_scrapes,json=successfulScrapes,proto3" json:"successful_scrapes,omitempty"`
	FailedScrapes     int32                  `protobuf:"varint,5,opt,name=failed_scrapes,json=failedScrapes,proto3" json:"failed_scrapes,omitempty"`
	Listings          []*Listing             `protobuf:"bytes,6,rep,name=listings,proto3" json:"listings,omitempty"`
	Errors            []string               `protobuf:"bytes,7,rep,name=errors,proto3" json:"errors,omitempty"`
	StartedAt         string                 `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt       string                 `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs        int64                  `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BatchResult) Reset() {
	*x = BatchResult{}
	mi := &file_proto_listing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResult) ProtoMessage() {}

func (x *BatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResult.ProtoReflect.Descriptor instead.
func (*BatchResult) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{7}
}

func (x *BatchResult) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *BatchResult) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *BatchResult) GetTotalListings() int32 {
	if x != nil {
		return x.TotalListings
	}
	return 0
}

func (x *BatchResult) GetSuccessfulScrapes() int32 {
	if x != nil {
		return x.SuccessfulScrapes
	}
	return 0
}

func (x *BatchResult) GetFailedScrapes() int32 {
	if x != nil {
		return x.FailedScrapes
	}
	return 0
}

func (x *BatchResult) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *BatchResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BatchResult) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *BatchResult) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *BatchResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_proto_listing_proto protoreflect.FileDescriptor

const file_proto_listing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/listing.proto\x12\alisting\"\x99\x03\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\rpersonal_info\x18\x02 \x01(\v2\x15.listing.PersonalInfoR\fpersonalInfo\x127\n" +
	"\fcontact_info\x18\x03 \x01(\v2\x14.listing.ContactInfoR\vcontactInfo\x127\n" +
	"\fpricing_info\x18\x04 \x01(\v2\x14.listing.PricingInfoR\vpricingInfo\x127\n" +
	"\fservice_info\x18\x05 \x01(\v2\x14.listing.ServiceInfoR\vserviceInfo\x12:\n" +
	"\rlocation_info\x18\x06 \x01(\v2\x15.listing.LocationInfoR\flocationInfo\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12!\n" +
	"\flast_updated\x18\b \x01(\tR\vlastUpdated\x12\x16\n" +
	"\x06photos\x18\t \x03(\tR\x06photos\"\xf6\x01\n" +
	"\fPersonalInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12\x1f\n" +
	"\vbreast_size\x18\x05 \x01(\x05R\n" +
	"breastSize\x12\x1d\n" +
	"\n" +
	"hair_color\x18\x06 \x01(\tR\thairColor\x12\x1b\n" +
	"\teye_color\x18\a \x01(\tR\beyeColor\x12\x1b\n" +
	"\tbody_type\x18\b \x01(\tR\bbodyType\x12\x16\n" +
	"\x06photos\x18\t \x03(\tR\x06photos\"\xb3\x01\n" +
	"\vContactInfo\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12!\n" +
	"\fhas_telegram\x18\x02 \x01(\bR\vhasTelegram\x12!\n" +
	"\fhas_whatsapp\x18\x03 \x01(\bR\vhasWhatsapp\x12\x1b\n" +
	"\thas_viber\x18\x04 \x01(\bR\bhasViber\x12+\n" +
	"\x11telegram_username\x18\x05 \x01(\tR\x10telegramUsername\"\x8f\x01\n" +
	"\vPricingInfo\x12\x1d\n" +
	"\n" +
	"hour_price\x18\x01 \x01(\x05R\thourPrice\x12$\n" +
	"\x0etwo_hour_price\x18\x02 \x01(\x05R\ftwoHourPrice\x12\x1f\n" +
	"\vnight_price\x18\x03 \x01(\x05R\n" +
	"nightPrice\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"K\n" +
	"\vServiceInfo\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xbd\x01\n" +
	"\fLocationInfo\x12%\n" +
	"\x0emetro_stations\x18\x01 \x03(\tR\rmetroStations\x12\x1a\n" +
	"\bdistrict\x18\x02 \x01(\tR\bdistrict\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12+\n" +
	"\x11outcall_available\x18\x04 \x01(\bR\x10outcallAvailable\x12)\n" +
	"\x10incall_available\x18\x05 \x01(\bR\x0fincallAvailable\"\xaf\x01\n" +
	"\bPageInfo\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNext\x12!\n" +
	"\fhas_previous\x18\x04 \x01(\bR\vhasPrevious\x12!\n" +
	"\flisting_urls\x18\x05 \x03(\tR\vlistingUrls\"\xf7\x02\n" +
	"\vBatchResult\x12\x1f\n" +
	"\vtotal_pages\x18\x01 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x02 \x01(\x05R\vcurrentPage\x12%\n" +
	"\x0etotal_listings\x18\x03 \x01(\x05R\rtotalListings\x12-\n" +
	"\x12successful_scrapes\x18\x04 \x01(\x05R\x11successfulScrapes\x12%\n" +
	"\x0efailed_scrapes\x18\x05 \x01(\x05R\rfailedScrapes\x12,\n" +
	"\blistings\x18\x06 \x03(\v2\x10.listing.ListingR\blistings\x12\x16\n" +
	"\x06errors\x18\a \x03(\tR\x06errors\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\t \x01(\tR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x03R\n" +
	"durationMsB,Z*github.com/gregor-tokarev/hoe_parser/protob\x06proto3"

var (
	file_proto_listing_proto_rawDescOnce sync.Once
	file_proto_listing_proto_rawDescData []byte
)

func file_proto_listing_proto_rawDescGZIP() []byte {
	file_proto_listing_proto_rawDescOnce.Do(func() {
		file_proto_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_listing_proto_rawDesc), len(file_proto_listing_proto_rawDesc)))
	})
	return file_proto_listing_proto_rawDescData
}

var file_proto_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_listing_proto_goTypes = []any{
	(*Listing)(nil),      // 0: listing.Listing
	(*PersonalInfo)(nil), // 1: listing.PersonalInfo
	(*ContactInfo)(nil),  // 2: listing.ContactInfo
	(*PricingInfo)(nil),  // 3: listing.PricingInfo
	(*ServiceInfo)(nil),  // 4: listing.ServiceInfo
	(*LocationInfo)(nil), // 5: listing.LocationInfo
	(*PageInfo)(nil),     // 6: listing.PageInfo
	(*BatchResult)(nil),  // 7: listing.BatchResult
}
var file_proto_listing_proto_depIdxs = []int32{
	1, // 0: listing.Listing.personal_info:type_name -> listing.PersonalInfo
	2, // 1: listing.Listing.contact_info:type_name -> listing.ContactInfo
	3, // 2: listing.Listing.pricing_info:type_name -> listing.PricingInfo
	4, // 3: listing.Listing.service_info:type_name -> listing.ServiceInfo
	5, // 4: listing.Listing.location_info:type_name -> listing.LocationInfo
	0, // 5: listing.BatchResult.listings:type_name -> listing.Listing
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_listing_proto_init() }
func file_proto_listing_proto_init() {
	if File_proto_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_listing_proto_rawDesc), len(file_proto_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_listing_proto_goTypes,
		DependencyIndexes: file_proto_listing_proto_depIdxs,
		MessageInfos:      file_proto_listing_proto_msgTypes,
	}.Build()
	File_proto_listing_proto = out.File
	file_proto_listing_proto_goTypes = nil
	file_proto_listing_proto_depIdxs = nil
}
