// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/listing.proto

package listing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main listing information
type Listing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PersonalInfo  *PersonalInfo          `protobuf:"bytes,2,opt,name=personal_info,json=personalInfo,proto3" json:"personal_info,omitempty"`
	ContactInfo   *ContactInfo           `protobuf:"bytes,3,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	PricingInfo   *PricingInfo           `protobuf:"bytes,4,opt,name=pricing_info,json=pricingInfo,proto3" json:"pricing_info,omitempty"`
	ServiceInfo   *ServiceInfo           `protobuf:"bytes,5,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	LocationInfo  *LocationInfo          `protobuf:"bytes,6,opt,name=location_info,json=locationInfo,proto3" json:"location_info,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	LastUpdated   string                 `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Photos        []string               `protobuf:"bytes,9,rep,name=photos,proto3" json:"photos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_proto_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Listing) GetPersonalInfo() *PersonalInfo {
	if x != nil {
		return x.PersonalInfo
	}
	return nil
}

func (x *Listing) GetContactInfo() *ContactInfo {
	if x != nil {
		return x.ContactInfo
	}
	return nil
}

func (x *Listing) GetPricingInfo() *PricingInfo {
	if x != nil {
		return x.PricingInfo
	}
	return nil
}

func (x *Listing) GetServiceInfo() *ServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

func (x *Listing) GetLocationInfo() *LocationInfo {
	if x != nil {
		return x.LocationInfo
	}
	return nil
}

func (x *Listing) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Listing) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *Listing) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

// Personal information
type PersonalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Weight        int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	BreastSize    int32                  `protobuf:"varint,5,opt,name=breast_size,json=breastSize,proto3" json:"breast_size,omitempty"`
	HairColor     string                 `protobuf:"bytes,6,opt,name=hair_color,json=hairColor,proto3" json:"hair_color,omitempty"`
	EyeColor      string                 `protobuf:"bytes,7,opt,name=eye_color,json=eyeColor,proto3" json:"eye_color,omitempty"`
	BodyType      string                 `protobuf:"bytes,8,opt,name=body_type,json=bodyType,proto3" json:"body_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalInfo) Reset() {
	*x = PersonalInfo{}
	mi := &file_proto_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInfo) ProtoMessage() {}

func (x *PersonalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInfo.ProtoReflect.Descriptor instead.
func (*PersonalInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{1}
}

func (x *PersonalInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonalInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PersonalInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PersonalInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PersonalInfo) GetBreastSize() int32 {
	if x != nil {
		return x.BreastSize
	}
	return 0
}

func (x *PersonalInfo) GetHairColor() string {
	if x != nil {
		return x.HairColor
	}
	return ""
}

func (x *PersonalInfo) GetEyeColor() string {
	if x != nil {
		return x.EyeColor
	}
	return ""
}

func (x *PersonalInfo) GetBodyType() string {
	if x != nil {
		return x.BodyType
	}
	return ""
}

// Contact information
type ContactInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Phone             string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Telegram          string                 `protobuf:"bytes,2,opt,name=telegram,proto3" json:"telegram,omitempty"`
	Email             string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	WhatsappAvailable bool                   `protobuf:"varint,4,opt,name=whatsapp_available,json=whatsappAvailable,proto3" json:"whatsapp_available,omitempty"`
	ViberAvailable    bool                   `protobuf:"varint,5,opt,name=viber_available,json=viberAvailable,proto3" json:"viber_available,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContactInfo) Reset() {
	*x = ContactInfo{}
	mi := &file_proto_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfo) ProtoMessage() {}

func (x *ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfo.ProtoReflect.Descriptor instead.
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{2}
}

func (x *ContactInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ContactInfo) GetTelegram() string {
	if x != nil {
		return x.Telegram
	}
	return ""
}

func (x *ContactInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactInfo) GetWhatsappAvailable() bool {
	if x != nil {
		return x.WhatsappAvailable
	}
	return false
}

func (x *ContactInfo) GetViberAvailable() bool {
	if x != nil {
		return x.ViberAvailable
	}
	return false
}

// Pricing information
type PricingInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DurationPrices map[string]int32       `protobuf:"bytes,1,rep,name=duration_prices,json=durationPrices,proto3" json:"duration_prices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // duration -> price
	ServicePrices  map[string]int32       `protobuf:"bytes,2,rep,name=service_prices,json=servicePrices,proto3" json:"service_prices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`    // service -> additional price
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PricingInfo) Reset() {
	*x = PricingInfo{}
	mi := &file_proto_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingInfo) ProtoMessage() {}

func (x *PricingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingInfo.ProtoReflect.Descriptor instead.
func (*PricingInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{3}
}

func (x *PricingInfo) GetDurationPrices() map[string]int32 {
	if x != nil {
		return x.DurationPrices
	}
	return nil
}

func (x *PricingInfo) GetServicePrices() map[string]int32 {
	if x != nil {
		return x.ServicePrices
	}
	return nil
}

func (x *PricingInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Service information
type ServiceInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AvailableServices  []string               `protobuf:"bytes,1,rep,name=available_services,json=availableServices,proto3" json:"available_services,omitempty"`
	AdditionalServices []string               `protobuf:"bytes,2,rep,name=additional_services,json=additionalServices,proto3" json:"additional_services,omitempty"`
	Restrictions       []string               `protobuf:"bytes,3,rep,name=restrictions,proto3" json:"restrictions,omitempty"`
	MeetingType        string                 `protobuf:"bytes,4,opt,name=meeting_type,json=meetingType,proto3" json:"meeting_type,omitempty"` // apartment, hotel, etc.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceInfo) GetAvailableServices() []string {
	if x != nil {
		return x.AvailableServices
	}
	return nil
}

func (x *ServiceInfo) GetAdditionalServices() []string {
	if x != nil {
		return x.AdditionalServices
	}
	return nil
}

func (x *ServiceInfo) GetRestrictions() []string {
	if x != nil {
		return x.Restrictions
	}
	return nil
}

func (x *ServiceInfo) GetMeetingType() string {
	if x != nil {
		return x.MeetingType
	}
	return ""
}

// Location information
type LocationInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MetroStations    []string               `protobuf:"bytes,1,rep,name=metro_stations,json=metroStations,proto3" json:"metro_stations,omitempty"`
	District         string                 `protobuf:"bytes,2,opt,name=district,proto3" json:"district,omitempty"`
	City             string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	OutcallAvailable bool                   `protobuf:"varint,4,opt,name=outcall_available,json=outcallAvailable,proto3" json:"outcall_available,omitempty"`
	IncallAvailable  bool                   `protobuf:"varint,5,opt,name=incall_available,json=incallAvailable,proto3" json:"incall_available,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LocationInfo) Reset() {
	*x = LocationInfo{}
	mi := &file_proto_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationInfo) ProtoMessage() {}

func (x *LocationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationInfo.ProtoReflect.Descriptor instead.
func (*LocationInfo) Descriptor() ([]byte, []int) {
	return file_proto_listing_proto_rawDescGZIP(), []int{5}
}

func (x *LocationInfo) GetMetroStations() []string {
	if x != nil {
		return x.MetroStations
	}
	return nil
}

func (x *LocationInfo) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *LocationInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *LocationInfo) GetOutcallAvailable() bool {
	if x != nil {
		return x.OutcallAvailable
	}
	return false
}

func (x *LocationInfo) GetIncallAvailable() bool {
	if x != nil {
		return x.IncallAvailable
	}
	return false
}

var File_proto_listing_proto protoreflect.FileDescriptor

const file_proto_listing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/listing.proto\x12\alisting\"\x99\x03\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\rpersonal_info\x18\x02 \x01(\v2\x15.listing.PersonalInfoR\fpersonalInfo\x127\n" +
	"\fcontact_info\x18\x03 \x01(\v2\x14.listing.ContactInfoR\vcontactInfo\x127\n" +
	"\fpricing_info\x18\x04 \x01(\v2\x14.listing.PricingInfoR\vpricingInfo\x127\n" +
	"\fservice_info\x18\x05 \x01(\v2\x14.listing.ServiceInfoR\vserviceInfo\x12:\n" +
	"\rlocation_info\x18\x06 \x01(\v2\x15.listing.LocationInfoR\flocationInfo\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12!\n" +
	"\flast_updated\x18\b \x01(\tR\vlastUpdated\x12\x16\n" +
	"\x06photos\x18\t \x03(\tR\x06photos\"\xde\x01\n" +
	"\fPersonalInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12\x1f\n" +
	"\vbreast_size\x18\x05 \x01(\x05R\n" +
	"breastSize\x12\x1d\n" +
	"\n" +
	"hair_color\x18\x06 \x01(\tR\thairColor\x12\x1b\n" +
	"\teye_color\x18\a \x01(\tR\beyeColor\x12\x1b\n" +
	"\tbody_type\x18\b \x01(\tR\bbodyType\"\xad\x01\n" +
	"\vContactInfo\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\btelegram\x18\x02 \x01(\tR\btelegram\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12-\n" +
	"\x12whatsapp_available\x18\x04 \x01(\bR\x11whatsappAvailable\x12'\n" +
	"\x0fviber_available\x18\x05 \x01(\bR\x0eviberAvailable\"\xd1\x02\n" +
	"\vPricingInfo\x12Q\n" +
	"\x0fduration_prices\x18\x01 \x03(\v2(.listing.PricingInfo.DurationPricesEntryR\x0edurationPrices\x12N\n" +
	"\x0eservice_prices\x18\x02 \x03(\v2'.listing.PricingInfo.ServicePricesEntryR\rservicePrices\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x1aA\n" +
	"\x13DurationPricesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a@\n" +
	"\x12ServicePricesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xb4\x01\n" +
	"\vServiceInfo\x12-\n" +
	"\x12available_services\x18\x01 \x03(\tR\x11availableServices\x12/\n" +
	"\x13additional_services\x18\x02 \x03(\tR\x12additionalServices\x12\"\n" +
	"\frestrictions\x18\x03 \x03(\tR\frestrictions\x12!\n" +
	"\fmeeting_type\x18\x04 \x01(\tR\vmeetingType\"\xbd\x01\n" +
	"\fLocationInfo\x12%\n" +
	"\x0emetro_stations\x18\x01 \x03(\tR\rmetroStations\x12\x1a\n" +
	"\bdistrict\x18\x02 \x01(\tR\bdistrict\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12+\n" +
	"\x11outcall_available\x18\x04 \x01(\bR\x10outcallAvailable\x12)\n" +
	"\x10incall_available\x18\x05 \x01(\bR\x0fincallAvailableB4Z2github.com/gregor-tokarev/hoe_parser/proto/listingb\x06proto3"

var (
	file_proto_listing_proto_rawDescOnce sync.Once
	file_proto_listing_proto_rawDescData []byte
)

func file_proto_listing_proto_rawDescGZIP() []byte {
	file_proto_listing_proto_rawDescOnce.Do(func() {
		file_proto_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_listing_proto_rawDesc), len(file_proto_listing_proto_rawDesc)))
	})
	return file_proto_listing_proto_rawDescData
}

var file_proto_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_listing_proto_goTypes = []any{
	(*Listing)(nil),      // 0: listing.Listing
	(*PersonalInfo)(nil), // 1: listing.PersonalInfo
	(*ContactInfo)(nil),  // 2: listing.ContactInfo
	(*PricingInfo)(nil),  // 3: listing.PricingInfo
	(*ServiceInfo)(nil),  // 4: listing.ServiceInfo
	(*LocationInfo)(nil), // 5: listing.LocationInfo
	nil,                  // 6: listing.PricingInfo.DurationPricesEntry
	nil,                  // 7: listing.PricingInfo.ServicePricesEntry
}
var file_proto_listing_proto_depIdxs = []int32{
	1, // 0: listing.Listing.personal_info:type_name -> listing.PersonalInfo
	2, // 1: listing.Listing.contact_info:type_name -> listing.ContactInfo
	3, // 2: listing.Listing.pricing_info:type_name -> listing.PricingInfo
	4, // 3: listing.Listing.service_info:type_name -> listing.ServiceInfo
	5, // 4: listing.Listing.location_info:type_name -> listing.LocationInfo
	6, // 5: listing.PricingInfo.duration_prices:type_name -> listing.PricingInfo.DurationPricesEntry
	7, // 6: listing.PricingInfo.service_prices:type_name -> listing.PricingInfo.ServicePricesEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_listing_proto_init() }
func file_proto_listing_proto_init() {
	if File_proto_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_listing_proto_rawDesc), len(file_proto_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_listing_proto_goTypes,
		DependencyIndexes: file_proto_listing_proto_depIdxs,
		MessageInfos:      file_proto_listing_proto_msgTypes,
	}.Build()
	File_proto_listing_proto = out.File
	file_proto_listing_proto_goTypes = nil
	file_proto_listing_proto_depIdxs = nil
}
