# HOE Parser Configuration

server:
  host: "localhost"
  port: 8080
  timeout: 30s

logging:
  level: "info"
  format: "json"
  output: "stdout"

parser:
  max_input_size: 1048576  # 1MB
  timeout: 60s
  workers: 4

database:
  host: "localhost"
  port: 5432
  name: "hoe_parser"
  user: "postgres"
  password: "password"
  ssl_mode: "disable"
  max_connections: 10

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

features:
  enable_caching: true
  enable_metrics: true
  enable_tracing: false 